[project]
name = "johnmamapdfv2"
version = "0.1.0"
description = "Certificate & Attendance PDF generator"
readme = "README.md"
authors = [
    { name = "JohnEggz", email = "avocadojuiceav@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "eel>=0.18.2",
    "python-calamine>=0.8.2",
    "rich>=15.0.0",
    "typst>=0.15.0",
]

[project.scripts]
johnmamapdfv2 = "johnmamapdfv2.app:run"
generator-launcher = "launcher.launcher:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/johnmamapdfv2",
    "src/launcher",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pyinstaller>=6.0.0",
]
